name: GitHub Profile Summary Cards

on:
  # Automatically run every Sunday at midnight
  schedule:
    - cron: '0 0 * * 0'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate GitHub Profile Summary Cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: Savvythelegend
          UTC_OFFSET: 5.5
        env:
          GITHUB_TOKEN: ${{ secrets.PROFILE_CARDS_TOKEN }}
