name: Update README

on:
  schedule:
    - cron: "*/30 * * * *"  # Every 30 minutes
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Update recent GitHub activity
        uses: jamesgeorge007/github-activity-readme@v0.3.0
        with:
          GH_USERNAME: irfan-iiitr
          COMMIT_MSG: "⚡ Update recent activity"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
